name: Action
on: push

jobs:
  build_executable:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - uses: docker/build-push-action@v1.1.0
      - run: mkdir artifacts
      - run: tools/build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: build_results
          path: artifacts